name: Badge automation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Game_Levels:
    name: "Preparing Environment!"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"


      - name: "HTML Level-1 Application"
        run: |
          echo 'Started level-1 analysis'
          cd html-js-css/level-1
          html_level1_message=$([[ $(test -f ./badge-status.js && node badge-status.js) == Completed ]] && echo "Completed" || echo "NotCompleted")          
          html_level1_color=$([[ $(test -f ./badge-status.js && node badge-status.js) == Completed ]] && echo "green" || echo "red")
          echo "html_level1_message=$html_level1_message" >> $GITHUB_ENV
          echo "html_level1_color=$html_level1_color" >> $GITHUB_ENV
          echo "html message: $html_level1_message"
          echo "html color: $html_level1_color"

      - name: "HTML Badge Level-1"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.auth }}
          gistID: ${{ secrets.HTML_LEVEL1 }}
          filename: html_level1.json
          label: HTML Level1
          message: ${{ env.html_level1_message }}
          color: ${{ env.html_level1_color }}

      - name: "React Level-1 Application"
        run: |
          echo 'Started level-1 analysis'
          cd react/level-1
          react_level1_message=$([[ $(test -f ./badge-status.js && node badge-status.js) == Completed ]] && echo "Completed" || echo "NotCompleted")          
          react_level1_color=$([[ $(test -f ./badge-status.js && node badge-status.js) == Completed ]] && echo "green" || echo "red")
          echo "react_level1_message=$react_level1_message" >> $GITHUB_ENV
          echo "react_level1_color=$react_level1_color" >> $GITHUB_ENV
          echo "react message: $react_level1_message"
          echo "react color: $react_level1_color"

      - name: "React Badge Level-1"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.auth }}
          gistID: ${{ secrets.REACT_LEVEL1 }}
          filename: react_level1.json
          label: React Level1
          message: ${{ env.react_level1_message }}
          color: ${{ env.react_level1_color }}

      - name: "DHIS2 Level-1 Application"
        run: |
          echo 'Started level-1 analysis'
          cd dhis2/level-1
          level1_message=$([[ $(test -f ./badge-status.js && node badge-status.js) == Completed ]] && echo "Completed" || echo "NotCompleted")          
          level1_color=$([[ $(test -f ./badge-status.js && node badge-status.js) == Completed ]] && echo "green" || echo "red")
          echo "level1_message=$level1_message" >> $GITHUB_ENV
          echo "level1_color=$level1_color" >> $GITHUB_ENV
          echo "secret: ${{secrets.REACT_LEVEL1}}"

      - name: "DHIS2 Level-1 badge"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.auth }}
          gistID: ${{ secrets.DHIS2_LEVEL1 }}
          filename: dhis2_level1.json
          label: DHIS2 Level1
          message: ${{ env.level1_message }}
          color: ${{ env.level1_color }}

      - name: "DHIS2 Level-2 application"
        run: |
          echo 'Level-1 Status:'
          echo 'Started level-2 analysis'
          cd dhis2/level-2
          level2_message=$([[ $(test -f ./badge-status.js && node badge-status.js) == Completed ]] && echo "Completed" || echo "NotCompleted")          
          level2_color=$([[ $(test -f ./badge-status.js && node badge-status.js) == Completed ]] && echo "green" || echo "red")
          echo "level2_message=$level2_message" >> $GITHUB_ENV
          echo "level2_color=$level2_color" >> $GITHUB_ENV

      - name: "DHIS2 Level-2 badge"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.auth }}
          gistID: ${{ secrets.DHIS2_LEVEL2 }}
          filename: dhis2_level2.json
          label: DHIS2 Level2
          message: ${{ env.level2_message }}
          color: ${{ env.level2_color }}
